#config_version=6

mode:
  start_events: start_mode_thwarting_a_robbery
  priority: 300
  stop_events: stop_mode_thwarting_a_robbery

shots:
  q_rob_1: { switch: s_right_ramp_made, profile: single_hit }
  q_rob_2: { switch: s_left_inlane,     profile: single_hit }
  q_rob_3: { switch: s_center_vuk,      profile: single_hit }

counters:
  q_rob_seq:
    count_events: (q_rob_1_complete, q_rob_2_complete, q_rob_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: thwarting_a_robbery_complete

event_player:
  thwarting_a_robbery_complete:
    - stop_mode_thwarting_a_robbery
    - start_mode_would_you_like_to_dance
