#config_version=6

mode:
  start_events: start_mode_the_prince_awakens
  priority: 300
  stop_events: stop_mode_the_prince_awakens

shots:
  z_awaken_1: { switch: s_left_ramp_made,  profile: single_hit }
  z_awaken_2: { switch: s_right_ramp_made, profile: single_hit }
  z_awaken_3: { switch: s_center_vuk,      profile: single_hit }
  z_awaken_4: { switch: s_spinner,         profile: single_hit }
  z_awaken_5: { switch: s_left_inlane,     profile: single_hit }
  z_awaken_6: { switch: s_right_inlane,    profile: single_hit }

counters:
  z_awaken_seq:
    count_events: (z_awaken_1_complete, z_awaken_2_complete, z_awaken_3_complete, z_awaken_4_complete, z_awaken_5_complete, z_awaken_6_complete)
    count_complete_value: 6
    reset_on_complete: true
    events_when_complete: the_prince_awakens_complete

event_player:
  the_prince_awakens_complete:
    - stop_mode_the_prince_awakens
    - start_mode_bubble_bath

