#config_version=6

# modes/attract/config/attract.yaml
mode:
  start_events: reset_complete
  stop_events: game_starting
  priority: 10

mode_settings:
  selectable_items:
    - title
    - credits
    - mpf_logo
    - last_scores_1p{machine.player1_score and not machine.player2_score}
    - last_scores_2p{machine.player2_score and not machine.player3_score}
    - last_scores_3p{machine.player3_score and not machine.player4_score}
    - last_scores_4p{machine.player4_score}
  next_item_events: s_right_flipper_active, timer_attract_carousel_timer_complete
  previous_item_events: s_left_flipper_active

slide_player:
  mode_attract_started: attract # slides/attract.tscn

sound_player:
  mode_attract_started:
    01_Opening Title Music-WAV:
      bus: music
  game_starting:
    01_Opening Title Music-WAV:
      action: stop

# Cycle through carousel items and pause during flipper cradle

timers:
  attract_carousel_timer:
    start_running: true
    end_value: 1
    tick_interval: 5s
    control_events:
      - event: item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart
