#config_version=6

# modes/attract/config/attract.yaml
mode:
  start_events: mode_attract_started
  priority: 10

mode_settings:
  selectable_items:
    - title
    - credits
    - mpf_logo
    - last_scores_1p{machine.player1_score and not machine.player2_score}
    - last_scores_2p{machine.player2_score and not machine.player3_score}
    - last_scores_3p{machine.player3_score and not machine.player4_score}
    - last_scores_4p{machine.player4_score}
  next_item_events: s_flipper_right_active, timer_attract_carousel_timer_complete
  previous_item_events: s_flipper_left_active

slide_player:
  mode_attract_started: attract   # slides/attract.tscn

sound_player:
  mode_attract_started:
    intro_music:
      bus: music
  game_starting:
    intro_music:
      action: stop
  game_started:
    intro_music:
      action: stop

timers:
  attract_carousel_timer:
    start_running: true
    end_value: 1
    tick_interval: 5s
    control_events:
      - event: item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart

# NEW: Start button → ask MPF to start a game (credits/free play checks happen automatically)
event_player:
  s_start_active: request_to_start_game
