#config_version=6

# modes/base/config/base.yaml
# Base mode starts on game start, shows a blocking location chooser,
# and launches either Queens or Zamunda based on selection.

mode:
  start_events: game_started
  priority: 100
  stop_events: base_done

# Block game flow until player picks a location
queue_event_player:
  mode_base_started:
    queue_event: prompt_location_choice
    events_when_finished: location_choice_done

# Show the chooser slide; clear the queue when either selection event fires
queue_relay_player:
  prompt_location_choice:
    post: show_location_choice
    wait_for: confirm_location_choice

# Display + audio
slide_player:
  show_location_choice: location_choice      # slides/location_choice.tscn (extends MPFSlide)

sound_player:
  show_location_choice: location_prompt.wav  # optional sting

# Selection state + defaults (0 = queens, 1 = zamunda)
variable_player:
  mode_base_started:
    selected_location:
      int: 0
  location_cursor_is_queens:
    selected_location: 0
  location_cursor_is_zamunda:
    selected_location: 1

# Two-state cursor controlled by cabinet inputs (and/or Godot UI)
state_machines:
  location_cursor:
    persist_state: true
    starting_state: queens
    states:
      queens:
        label: queens
        events_when_started: location_cursor_is_queens
      zamunda:
        label: zamunda
        events_when_started: location_cursor_is_zamunda
    transitions:
      - source: queens
        target: zamunda
        events: set_location_cursor_right
      - source: zamunda
        target: queens
        events: set_location_cursor_left

# Inputs + confirmation and final handoff
event_player:
  s_flipper_left_active: set_location_cursor_left
  s_flipper_right_active: set_location_cursor_right
  s_start_active: confirm_location_choice

  confirm_location_choice:
    - location_queens_selected{current_player.selected_location == 0}
    - location_zamunda_selected{current_player.selected_location == 1}

  # When the blocking queue finishes, launch the chosen branch and end base
  location_choice_done:
    - start_mode_queens{current_player.selected_location == 0}
    - start_mode_zamunda{current_player.selected_location == 1}
    - base_done
