#config_version=6

# modes/base/config/base.yaml
# Base mode starts on game start, shows a blocking location chooser,
# and launches either Queens or Zamunda based on selection.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_location_select{current_player.selected_location==0}
    - start_mode_queens{current_player.selected_location == 1}
    - start_mode_zamunda{current_player.selected_location == 2}

# Block game flow until player picks a location
queue_relay_player:
  balldevice_bd_trough_eject_attempt{current_player.selected_location==0}:
    post: wait_for_location_choice
    wait_for: location_choice_done

slide_player:
  mode_base_started: base