#config_version=6

mode:
  start_events: start_mode_searching_for_a_queen
  priority: 300
  stop_events: stop_mode_searching_for_a_queen

shots:
  q_search_1: { switch: s_left_ramp_made,  profile: single_hit }
  q_search_2: { switch: s_right_ramp_made, profile: single_hit }
  q_search_3: { switch: s_spinner,         profile: single_hit }

counters:
  q_search_seq:
    count_events: (q_search_1_complete, q_search_2_complete, q_search_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: searching_for_a_queen_complete

event_player:
  searching_for_a_queen_complete:
    - stop_mode_searching_for_a_queen
    - start_mode_the_barbershop

