#config_version=8

mode:
  start_events: start_mode_king_collects_son
  priority: 300
  stop_events: stop_mode_king_collects_son

shots:
  q_king_1: { switch: s_left_orbit_made,  profile: single_hit }
  q_king_2: { switch: s_right_orbit_made, profile: single_hit }
  q_king_3: { switch: s_center_vuk,       profile: single_hit }

counters:
  q_king_seq:
    count_events: (q_king_1_complete, q_king_2_complete, q_king_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: king_collects_son_complete

event_player:
  king_collects_son_complete:
    - stop_mode_king_collects_son
