#config_version=8

mode:
  start_events: start_mode_basketball_date
  priority: 300
  stop_events: stop_mode_basketball_date

shots:
  q_ball_1: { switch: s_left_orbit_made,  profile: single_hit }
  q_ball_2: { switch: s_right_orbit_made, profile: single_hit }
  q_ball_3: { switch: s_left_ramp_made,   profile: single_hit }

counters:
  q_ball_seq:
    count_events: (q_ball_1_complete, q_ball_2_complete, q_ball_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: basketball_date_complete

event_player:
  basketball_date_complete:
    - stop_mode_basketball_date
    - start_mode_thwarting_a_robbery
