#config_version=8

mode:
  start_events: start_mode_would_you_like_to_dance
  priority: 300
  stop_events: stop_mode_would_you_like_to_dance

shots:
  q_dance_1: { switch: s_left_inlane,     profile: single_hit }
  q_dance_2: { switch: s_right_inlane,    profile: single_hit }
  q_dance_3: { switch: s_right_orbit_made, profile: single_hit }

counters:
  q_dance_seq:
    count_events: (q_dance_1_complete, q_dance_2_complete, q_dance_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: would_you_like_to_dance_complete

event_player:
  would_you_like_to_dance_complete:
    - stop_mode_would_you_like_to_dance
    - start_mode_pleading_your_case
