#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml
  - config_lights.yaml
  - config_displays.yaml
  - modes.yaml

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough

# Enable Credits mode with permanent free play
credits:
  enabled: true
  free_play: true
  free_play_string: "FREE PLAY"
