#config_version=6
switches:
  # Cabinet buttons (Cabinet I/O)
  s_start: { number: cab-11, tags: start } # start button
  s_tilt_bob: { number: cab-9, tags: tilt } # plumb-bob tilt
  s_tilt_warning: { number: cab-12, tags: tilt_warning } # optional warn
  #s_coin:          { number: cab-3 }

  s_left_flipper: { number: cab-10, tags: left_flipper }
  s_right_flipper: { number: cab-16, tags: right_flipper }

  # EOS (on the lower playfield node 3208)
  s_left_eos: { number: pf_lower-2 }
  s_right_eos: { number: pf_lower-1 }

  # Trough & shooter (lower playfield 3208)
  s_trough_1: { number: pf_lower-8 }
  s_trough_2: { number: pf_lower-9 }
  s_trough_3: { number: pf_lower-10 }
  s_trough_4: { number: pf_lower-11 }
  s_trough_5: { number: pf_lower-12 }
  s_trough_6: { number: pf_lower-13 }
  s_trough_jam: { number: pf_lower-14 }
  s_shooter_lane: { number: pf_lower-15 }

  # A couple of playfield switches for testing flips & scoring
  s_left_inlane:   { number: pf_lower-16 }
  s_right_inlane:  { number: pf_lower-17 }

  # Orbits, ramps, spinner (placeholders on pf_lower)
  s_left_orbit_made:  { number: pf_lower-5 }
  s_right_orbit_made: { number: pf_lower-6 }
  s_left_ramp_made:   { number: pf_lower-7 }
  s_right_ramp_made:  { number: pf_lower-18 }
  s_spinner:          { number: pf_lower-19 }


  # Stern "SOUL" smart drop target bank
  s_soul_s: { number: pf_upper-4, tags: drop_target }
  s_soul_o: { number: pf_upper-5, tags: drop_target }
  s_soul_u: { number: pf_upper-6, tags: drop_target }
  s_soul_l: { number: pf_upper-7, tags: drop_target }

  # "GLO" drop target bank
  s_glo_g: { number: pf_upper-13, tags: drop_target }
  s_glo_l: { number: pf_upper-14, tags: drop_target }
  s_glo_o: { number: pf_upper-15, tags: drop_target }

  # Left ramp single drop target
  s_left_ramp_drop: { number: pf_upper-12, tags: drop_target }
  # Upper playfield VUK
  s_center_vuk: { number: pf_upper-3, tags: vuk }

  # McDowell inline (Metallica-style) drops under VUK
  s_mcdowell_inline_1: { number: pf_upper-0, tags: drop_target }
  s_mcdowell_inline_2: { number: pf_upper-1, tags: drop_target }
  s_mcdowell_inline_3: { number: pf_upper-2, tags: drop_target }

  # Upper pop bumper
  s_upper_pop: { number: pf_upper-11, tags: popbumper }

