#config_version=6
coils:
  # Flippers (dual-wound on pf_lower drivers 2-7)
  c_left_flipper_main: { number: pf_lower-7, default_pulse_ms: 30, label: "c_left_flipper_main" }
  c_left_flipper_hold:
    { number: pf_lower-6, default_pulse_ms: 0, default_hold_power: 0.99, label: "c_left_flipper_hold"}
  c_right_flipper_main: { number: pf_lower-3, default_pulse_ms: 30, label: "c_right_flipper_main" }
  c_right_flipper_hold:
    { number: pf_lower-2, default_pulse_ms: 0, default_hold_power: 0.99, label: "c_right_flipper_hoild" }

  # Ball devices (pf_lower drivers 4 and 5)
  c_trough_eject: { number: pf_lower-4, default_pulse_ms: 25 , label: "c_trough_eject"}
  c_autoplunger: { number: pf_lower-5, default_pulse_ms: 20, label: "c_autoplunger" } # remove if manual plunge, label: "c_autoplunger"r

  # Slings (pf_lower drivers 0 and 1)
  c_right_sling: { number: pf_lower-1, default_pulse_ms: 12 , label: "c_right_sling"}
  c_left_sling: { number: pf_lower-0, default_pulse_ms: 12 , label: "c_left_sling"}

  # Upper playfield coils (FAST IO-1616 pf_upper)
  c_center_vuk: { number: pf_upper-12, default_pulse_ms: 35 , label: "c_center_vuk"}
  c_mcdowell_inline_reset: { number: pf_upper-13, default_pulse_ms: 40 , label: "c_mcdowell_inline_reset"}
  c_soul_drop_reset: { number: pf_upper-7, default_pulse_ms: 40, label: "c_soul_drop_reset" } # , label: "c_soul_drop_reset"F
  c_glo_drop_reset: { number: pf_upper-5, default_pulse_ms: 35, label: "c_glo_drop_reset" } # , label: "c_glo_drop_reset"D
  c_left_ramp_drop_reset: { number: pf_upper-10, default_pulse_ms: 35 , label: "c_left_ramp_drop_reset"}
  c_upper_pop: { number: pf_upper-15, default_pulse_ms: 40, label: c_upper_pop } #2, label: "c_upper_pop"B
  c_lower_pf_magnet: { number: pf_upper-11, tags: magnet , label: "c_lower_pf_magnet"}
  c_upper_pf_magnet: { number: pf_upper-14, tags: magnet , label: "c_upper_pf_magnet"}
