#config_version=6
# config/modes.yaml
modes:
  - attract
  - base
  - queens
  - zamunda

  # Queens sub-modes (order doesn????????t matter here????????start_events control flow)
  - arriving_in_queens
  - searching_for_a_queen
  - the_barbershop
  - miss_black_awareness
  - working_at_mcdowells
  - basketball_date
  - thwarting_a_robbery
  - would_you_like_to_dance
  - pleading_your_case
  - king_collects_son

  # Zamunda sub-modes
  - the_prince_awakens
  - bubble_bath
  - sparring_with_semmi
  - the_royal_wedding
  - a_royal_celebration

