#config_version=6

mode:
  start_events: start_mode_miss_black_awareness
  priority: 300
  stop_events: stop_mode_miss_black_awareness

shots:
  q_mba_1: { switch: s_right_orbit_made, profile: single_hit }
  q_mba_2: { switch: s_left_ramp_made,   profile: single_hit }
  q_mba_3: { switch: s_center_vuk,       profile: single_hit }

counters:
  q_mba_seq:
    count_events: (q_mba_1_complete, q_mba_2_complete, q_mba_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: miss_black_awareness_complete

event_player:
  miss_black_awareness_complete:
    - stop_mode_miss_black_awareness
    - start_mode_working_at_mcdowells

