#config_version=6

mode:
  start_events: start_mode_working_at_mcdowells
  priority: 300
  stop_events: stop_mode_working_at_mcdowells

shots:
  q_mcd_1: { switch: s_left_inlane,     profile: single_hit }
  q_mcd_2: { switch: s_right_ramp_made, profile: single_hit }
  q_mcd_3: { switch: s_spinner,         profile: single_hit }

counters:
  q_mcd_seq:
    count_events: (q_mcd_1_complete, q_mcd_2_complete, q_mcd_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: working_at_mcdowells_complete

event_player:
  working_at_mcdowells_complete:
    - stop_mode_working_at_mcdowells
    - start_mode_basketball_date

