#config_version=6

mode:
  start_events: start_mode_bubble_bath
  priority: 300
  stop_events: stop_mode_bubble_bath

shots:
  z_bath_1: { switch: s_left_orbit_made,  profile: single_hit }
  z_bath_2: { switch: s_right_orbit_made, profile: single_hit }
  z_bath_3: { switch: s_spinner,          profile: single_hit }

shot_groups:
  z_bath_seq:
    shots: z_bath_1, z_bath_2, z_bath_3
    advance_on_complete: true
    completion_events: bubble_bath_complete

event_player:
  bubble_bath_complete:
    - stop_mode_bubble_bath
    - start_mode_sparring_with_semmi
