#config_version=6

# Zamunda hub that auto-starts 'The Prince Awakens'.
mode:
  start_events: start_mode_zamunda
  priority: 200
  stop_events: stop_mode_zamunda

event_player:
  mode_zamunda_started: start_mode_the_prince_awakens

slide_player:
  mode_zamunda_started: zamunda