#config_version=6

mode:
  start_events: start_mode_the_royal_wedding
  priority: 300
  stop_events: stop_mode_the_royal_wedding

shots:
  z_wed_1: { switch: s_left_inlane,     profile: single_hit }
  z_wed_2: { switch: s_right_inlane,    profile: single_hit }
  z_wed_3: { switch: s_spinner,         profile: single_hit }

counters:
  z_wed_seq:
    count_events: (z_wed_1_complete, z_wed_2_complete, z_wed_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: the_royal_wedding_complete

event_player:
  the_royal_wedding_complete:
    - stop_mode_the_royal_wedding
    - start_mode_a_royal_celebration

