#config_version=6

# modes/base/config/base.yaml
# Base mode starts on game start, shows a blocking location chooser,
# and launches either Queens or Zamunda based on selection.

mode:
  start_events: start_mode_location_select
  stop_events: stop_mode_location_select
  priority: 500

# Display + audio
slide_player:
  mode_location_select_started: location_choice      # slides/location_choice.tscn (extends MPFSlide)
  # When the selected value changes, update the slide
  player_selected_location:
    location_choice:
      action: update

sound_player:
  mode_location_select_started:
    01_Opening Title Music-WAV:
      bus: music
  location_choice_done:
    01_Opening Title Music-WAV:
      action: stop

# Selection state + defaults (1 = queens, 2 = zamunda)

variable_player:
  mode_location_select_started:
    selected_location:
      int: 1
  set_location_queens:
    selected_location:
      action: set
      int: 1
  set_location_zamunda:
    selected_location:
      action: set
      int: 2

# Inputs + confirmation and final handoff
event_player:
  # Use the inactive event to prevent accidental changes
  # during the both-flippers-to-select presses
  s_left_flipper_inactive: set_location_queens
  s_right_flipper_inactive: set_location_zamunda
  flipper_cancel: location_choice_done
  # UI buttons also confirm the queue
  location_queens_selected: location_choice_done
  location_zamunda_selected: location_choice_done

  # When the blocking queue finishes, launch the chosen branch and end base
  location_choice_done.2:
    - start_mode_queens{current_player.selected_location == 1}
    - start_mode_zamunda{current_player.selected_location == 2}
  location_choice_done.1:
    - stop_mode_location_select
