#config_version=8

mode:
  start_events: start_mode_sparring_with_semmi
  priority: 300
  stop_events: stop_mode_sparring_with_semmi

shots:
  z_spar_1: { switch: s_left_ramp_made,   profile: single_hit }
  z_spar_2: { switch: s_right_ramp_made,  profile: single_hit }
  z_spar_3: { switch: s_center_vuk,       profile: single_hit }

counters:
  z_spar_seq:
    count_events: (z_spar_1_complete, z_spar_2_complete, z_spar_3_complete)
    count_complete_value: 3
    reset_on_complete: true
    events_when_complete: sparring_with_semmi_complete

event_player:
  sparring_with_semmi_complete:
    - stop_mode_sparring_with_semmi
    - start_mode_the_royal_wedding
